---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage 
summary: 您可以在 Cloud Volumes ONTAP 系统上激活一次写入、多次读取（ WORM ）存储、以在指定的保留期内以未经修改的形式保留文件。云 WORM 存储由 SnapLock 技术提供支持，这意味着 WORM 文件在文件级别受到保护。 
---
= WORM 存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在 Cloud Volumes ONTAP 系统上激活一次写入、多次读取（ WORM ）存储、以在指定的保留期内以未经修改的形式保留文件。云 WORM 存储由 SnapLock 技术提供支持，这意味着 WORM 文件在文件级别受到保护。



== WORM 存储的工作原理

将文件提交到 WORM 存储后，即使在保留期限到期后，也无法对其进行修改。防篡改时钟将确定 WORM 文件的保留期已过。

保留期结束后、您将负责删除不再需要的任何文件。



== 激活 WORM 存储

激活WORM存储的方式取决于所使用的Cloud Volumes ONTAP 版本。



=== 9.10.1及更高版本

从Cloud Volumes ONTAP 9.10.1开始、您可以选择在卷级别启用或禁用WORM。选择如何启用WORM取决于您的需求。

创建新的Cloud Volumes ONTAP 工作环境时、系统会提示您启用或禁用WORM存储：

* 如果在创建工作环境时启用了WORM存储、则从BlueXP创建的每个卷都会启用WORM。但是、您可以使用System Manager或CLI创建已禁用WORM的卷。
+
如果要为WORM存储创建专用系统、则此选项是一个不错的选择。

* 如果在创建工作环境时禁用WORM存储、则从BlueXP创建的每个卷都会禁用WORM。但是、您可以使用System Manager或命令行界面创建启用了WORM的卷。
+
如果要在同一系统上混用不同类型的卷、则此选项是一个不错的选择。



无论选择哪种方案、您都应选择此选项 <<正在充电,了解充电的工作原理>>。



=== 9.10.0及更早版本

您可以在创建新的工作环境时在 Cloud Volumes ONTAP 系统上激活 WORM 存储。您不能在单个卷上激活 WORM 存储—必须在系统级别激活 WORM 。只有在创建工作环境时、才能激活它。



== 正在充电

根据 WORM 卷的总配置容量， WORM 存储的费用为每小时一次。

您应了解Cloud Volumes ONTAP 9.10.1及更高版本的以下充电行为：

* 从ONTAP 9.10.1开始、WORM卷和非WORM卷可以位于同一聚合上。
* 如果在创建Cloud Volumes ONTAP 工作环境时启用了WORM、则从BlueXP创建的每个卷都会启用WORM。但是、您可以使用ONTAP 命令行界面或系统管理器创建已禁用WORM的卷。这些卷不按WORM速率充电。
* 如果在创建工作环境时未启用WORM、则从BlueXP创建的每个卷都会禁用WORM。这些卷不按WORM速率计费。但是、您可以使用ONTAP 命令行界面或系统管理器创建启用了WORM的卷。这些卷将按WORM速率收费。


https://cloud.netapp.com/pricing["了解 WORM 存储的定价"^]



== 将文件提交到 WORM

您可以使用应用程序通过 NFS 或 CIFS 将文件提交到 WORM ，或者使用 ONTAP CLI 自动将文件提交到 WORM 。您还可以使用 WORM 附加文件来保留增量写入的数据，例如日志信息。

在 Cloud Volumes ONTAP 系统上激活 WORM 存储后，必须使用 ONTAP CLI 对 WORM 存储进行所有管理。有关说明，请参见 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["ONTAP 文档"^]。



== 限制

* Cloud Volumes ONTAP 中的 WORM 存储在 " 可信存储管理员 " 模式下运行。虽然 WORM 文件不受更改或修改的影响，但集群管理员可以删除卷，即使这些卷包含未过期的 WORM 数据也是如此。
* 除了可信存储管理员模式之外， Cloud Volumes ONTAP 中的 WORM 存储还隐式地在 " 可信云管理员 " 模式下运行。云管理员可以通过直接从云提供商中删除或编辑云存储，在 WORM 数据到期之前将其删除。
* 激活 WORM 存储后，无法启用对象存储的数据分层。

