---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging 
summary: 熟悉基于容量的许可证的收费、使用模式、定价和配置。 
---
= 详细了解Cloud Volumes ONTAP基于容量的许可证
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您应熟悉基于容量的许可证的收费和容量使用情况



== 消费模式

基于容量的许可包可用于以下消费模式：

* *BYOL*：自带许可证(BYOL)。从NetApp购买的一种许可证、可用于在任何云提供商中部署Cloud Volumes ONTAP。
+

NOTE: NetApp已限制 BYOL 许可的购买、延期和续订。有关更多信息，请参阅 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Cloud Volumes ONTAP的 BYOL 许可可用性受限"^] 。



ifdef::azure[]

+请注意、优化包不支持BYOL。

endif::azure[]

* *PAYGO*：按需购买(PAYGO)订阅是云提供商市场上按小时订阅的服务。
* *年度*：云提供商市场提供的年度合同。


请注意以下事项：

* 如果您从NetApp购买了 BYOL 许可证，则还需要从云提供商的云市场订阅 PAYGO 产品。NetApp已限制 BYOL 许可。当您的 BYOL 许可证到期时，您需要将其替换为云市场订阅。
+
您的许可证始终会先付费，但在以下情况下，您将从市场上的每小时费率中扣除费用：

+
** 超出许可容量时
** 许可证期限到期时


* 如果您从某个市场签有年度合同，则您部署的 _all_ Cloud Volumes ONTAP 系统将从该合同中扣除费用。您不能将年度市场合同与 BYOL 混合搭配使用。
* 中国区域仅支持支持 BYOL 的单节点系统。中国区域部署不受 BYOL 许可限制。




== 更改软件包

部署后、您可以更改使用基于容量的许可的Cloud Volumes ONTAP 系统的软件包。例如、如果您使用Essentials软件包部署了Cloud Volumes ONTAP 系统、则可以在业务需求发生变化时将其更改为"Professional软件包"。

link:task-manage-capacity-licenses.html["了解如何更改充电方法"]。

有关将基于节点的许可证转换为基于容量的许可证的信息、请参见



== 定价和支持的配置

有关定价的详细信息，请访问 https://bluexp.netapp.com/pricing/["NetApp BlueXP网站"^]。

Cloud Volumes ONTAP 9.7 及更高版本提供了基于容量的许可包。



=== Storage VM

* 对于其他提供数据的 Storage VM （ SVM ），无需额外的许可成本，但每个提供数据的 SVM 的最低容量费用为 4 TiB 。
* 灾难恢复 SVM 会根据配置的容量进行收费。




=== HA 对

对于 HA 对，您只需为节点上的已配置容量付费。您无需为同步镜像到配对节点的数据付费。



=== FlexClone和FlexCache 卷

* FlexClone 卷使用的容量不会向您收取费用。
* 源和目标 FlexCache 卷被视为主数据，并根据配置的空间进行收费。




== Capacity limit

在此许可模式下，每个单独的 Cloud Volumes ONTAP 系统可通过磁盘和对象存储分层支持多达 2 个 PIB 的容量。

对于许可证本身，没有最大容量限制。



== 最大系统数

使用基于容量的许可，每个BlueXP帐户的Cloud Volumes ONTAP系统的最大数量限制为 24 个。_system_是指Cloud Volumes ONTAP HA对、Cloud Volumes ONTAP 单节点系统或您创建的任何其他Storage VM。默认Storage VM不计入此限制。这将限制适用场景 的所有许可模式。

例如、假设您有三个工作环境：

* 包含一个Storage VM的单节点Cloud Volumes ONTAP 系统(这是在部署Cloud Volumes ONTAP 时创建的默认Storage VM)
+
此工作环境可视为一个系统。

* 包含两个Storage VM (默认Storage VM加上您创建的一个额外Storage VM)的单节点Cloud Volumes ONTAP 系统
+
此工作环境分为两个系统：一个用于单节点系统、一个用于额外的Storage VM。

* 一个Cloud Volumes ONTAP HA对、其中包含三个Storage VM (默认Storage VM加上您创建的两个额外Storage VM)
+
此工作环境分为三个系统：一个用于HA对、两个用于额外的Storage VM。



总共有六个系统。然后、您的帐户中还可以再添加14个系统。

如果您的大型部署需要24个以上的系统、请联系您的客户代表或销售团队。

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-netapp-accounts.html["了解有关BlueXP帐户的更多信息"^](英文)

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["了解 AWS、Azure 和 Google Cloud 的存储限制"^](英文)



== 有关充电的注意事项

以下详细信息可帮助您了解收费如何与基于容量的许可配合使用。



=== 最低费用

对于至少具有一个主(读写)卷的每个提供数据的Storage VM、最低费用为4 TiB。如果主卷的总和小于4 TiB、则BlueXP会将4 TiB的最低费用应用于该Storage VM。

如果尚未配置任何卷、则最低费用不适用。

对于Essentials软件包、最低4 TiB容量费用不适用于仅包含二级(数据保护)卷的Storage VM。例如、如果您的Storage VM包含1 TiB的二级数据、则只需为1 TiB的数据付费。对于所有其他非Essentials封装类型(优化型和专业型)、无论卷类型如何、最低容量充电均为4 TiB。



=== 过剩

如果您超出了 BYOL 容量，我们将根据您的市场订阅按小时费率向您收取超额费用。超额部分将按市场费率收费，并优先使用其他许可证中的可用容量。如果您的 BYOL 许可证到期，您需要通过云市场过渡到基于容量的许可模式。



=== Essentials 软件包

通过Essentials软件包、您将按部署类型(HA或单个节点)和卷类型(主卷或二级卷)付费。从高到低的定价按以下顺序进行：_Essentials Primary HA_、_Essentials Primary Single Node_、_Essentials Secondary HA_和_Essentials Secondary Single Node_。或者、当您购买商城合同或接受私人报价时、任何部署或卷类型的容量费用都是相同的。

许可完全取决于在Cloud Volumes ONTAP系统中创建的卷类型：

* Essentials单节点：仅使用一个ONTAP节点在Cloud Volumes ONTAP系统上创建的读/写卷。
* Essentials HA：使用两个ONTAP节点的读/写卷、这些节点可以相互故障转移以实现无中断数据访问。
* Essentials辅助单节点：仅使用一个ONTAP节点在Cloud Volumes ONTAP系统上创建的数据保护(DP)类型卷(通常为只读SnapMirror或SnapVault目标卷)。
+

NOTE: 如果只读/DP卷成为主卷、则BlueXP  会将其视为主数据、并根据卷处于读/写模式的时间计算收费成本。当卷再次设为只读/DP时、BlueXP  会再次将其视为二级数据、并使用数字钱包中最匹配的许可证进行相应收费。

* Essentials二级HA：在使用两个ONTAP节点的Cloud Volumes ONTAP系统上创建的数据保护(DP)类型的卷(通常为只读SnapMirror或SnapVault目标卷)、这些节点可以相互故障转移以实现无中断数据访问。


.BYOL
如果您从NetApp (BYOL)购买了Essentials许可证、但超出了该部署和卷类型的许可容量、则BlueXP数字钱包会对价格较高的Essentials许可证(如果您拥有一个许可证且有可用容量)收取超额费用。这是因为我们首先使用您已购买的可用容量作为预付费容量、然后再向市场收费。如果您的BYOL许可证没有可用容量、则超出的容量将按市场按需每小时费率(PAYGO)收取、并会在您的月度账单中增加成本。

下面是一个示例。假设您已为Essentials软件包获得以下许可证：

* 一个500 TiB _Essentials二级HA_许可证、其已提交容量为500 TiB
* 500 TiB _Essentials单节点_许可证、仅具有100 TiB的已提交容量


另有50 TiB配置在具有二级卷的HA对上。BlueXP数字钱包不会向PAYGO收取50 TiB的费用、而是根据_Essentials Single Node_许可证收取50 TiB的超额费用。该许可证的价格高于_Essentials Secondary HA_、但它会使用您已购买的许可证、并且不会增加您的月度账单成本。

在BlueXP数字钱包中、该50 TiB将显示为已通过_Essentials Single Node_许可证付费。

下面是另一个示例。假设您已为Essentials软件包获得以下许可证：

* 一个500 TiB _Essentials二级HA_许可证、其已提交容量为500 TiB
* 500 TiB _Essentials单节点_许可证、仅具有100 TiB的已提交容量


在包含主卷的HA对上配置另一个100 TiB。您购买的许可证没有已提交的_Essentials主HA_容量。Essentials Primary HA_许可证的价格高于_Essentials Primary Single Node_和_Essentials Secondary HA_许可证的价格。

在此示例中、BlueXP数字钱包按市场费率额外收取100 TiB的超额费用。超额费用将显示在您的月度账单上。

.市场合同或私人报价
如果您在市场合同或私人优惠中购买了Essentials许可证、则BYOL逻辑不适用、您必须具有与此用途完全相同的许可证类型。许可证类型包括卷类型(主或二级)和部署类型(HA或单节点)。

例如、假设您使用Essentials许可证部署Cloud Volumes ONTAP实例。然后、您可以配置读写卷(主单节点)和只读卷(二级单节点)。您的商城合同或私人报价必须包含_Essentials Single Node_和_Essentials Secondary Single Node_的容量、以涵盖配置的容量。不属于您的商城合同或私人优惠的任何已配置容量将按按需每小时费率(PAYGO)收费、并将成本增加到您的月度账单中。
