---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: 'freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go, keystone flex, keystone, cloud backup, digital wallet, bluexp license conversion for node based, license end of support (EOS) node-based, end of availability (EOA) of node-based' 
summary: Cloud Volumes ONTAP 提供了多种许可选项。每个选项都可用于选择满足您需求的配置。 
---
= Cloud Volumes ONTAP 许可
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 提供了多种许可选项。每个选项都允许您选择一种满足您需求的消费模式。



== 许可概述

新客户可以使用以下许可选项。

基于容量的许可:: 按配置的容量为您的NetApp帐户中的多个Cloud Volumes ONTAP 系统付费。包括购买附加云数据服务的功能。有关基于容量的许可证中使用模式的详细信息，请参见link:concept-licensing-charging.html["详细了解基于容量的许可证"]。
Keystone订阅:: 一种基于订阅的按需购买服务、可为高可用性(HA)对提供无缝的混合云体验。


以下各节提供了有关其中每个选项的更多详细信息。


NOTE: 如果没有许可证、则不支持使用已获得许可的功能。



== 基于容量的许可

通过基于容量的许可包、您可以按每TiB容量为Cloud Volumes ONTAP 付费。此许可证与您的 NetApp 帐户关联，您可以使用此许可证向多个系统收取费用，前提是可通过此许可证获得足够的容量。

例如，您可以购买一个 20 TiB 许可证，部署四个 Cloud Volumes ONTAP 系统，然后为每个系统分配一个 5 TiB 卷，总共 20 TiB 。该容量可供在该帐户中部署的每个 Cloud Volumes ONTAP 系统上的卷使用。

基于容量的许可以 _package_ 的形式提供。部署Cloud Volumes ONTAP 系统时、您可以根据业务需求从多个许可包中进行选择。


NOTE: 虽然BlueXP中管理的产品和服务的实际使用情况和计量始终以GiB和TiB计算、但术语GB/GiB和TB/TiB可互换使用。这反映在云商城商品信息、报价、商品说明以及其他支持文档中。



=== 软件包

以下基于容量的软件包可用于Cloud Volumes ONTAP。有关基于容量的许可证包的详细信息，请参见link:concept-licensing-charging.html["详细了解基于容量的许可证"]。

有关以下基于容量的软件包支持的VM类型列表、请参见：

ifdef::azure[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Azure 中支持的配置"^]


endif::azure[]

ifdef::gcp[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Google Cloud 支持的配置"^]


endif::gcp[]



==== 免费

免费提供 NetApp 提供的所有 Cloud Volumes ONTAP 功能（仍需支付云提供商费用）。Freemium封装具有以下特征：

* 不需要许可证或合同。
* 不包括 NetApp 的支持。
* 每个 Cloud Volumes ONTAP 系统的已配置容量限制为 500 GiB 。
* 对于任何云提供商、每个NetApp帐户最多可以使用10个Cloud Volumes ONTAP系统以及免费增值服务。
* 如果为Cloud Volumes ONTAP系统配置的容量超过500 GiB、则BlueXP  会将系统转换为Essentials软件包。
+
一旦将系统转换为Essentials软件包、就会立即应用到该软件包link:concept-licensing-charging.html#minimum-charge["最小充电量"]。

+
已转换为Essentials软件包的Cloud Volumes ONTAP系统无法切换回Freemium、即使已配置的容量降至500 GiB以下也是如此。配置容量小于500 GiB的其他系统将保留在Freemium上(只要这些系统是使用Freemium产品部署的)。





==== 要点

您可以在多种不同配置中按容量付费：

* 选择 Cloud Volumes ONTAP 配置：
+
** 单节点或 HA 系统
** 用于灾难恢复（ DR ）的文件和块存储或二级数据


* 增加 NetApp 的任何云数据服务，但需额外付费




==== 已优化

单独为配置的容量和I/O操作付费。

* Cloud Volumes ONTAP 单节点或HA
* 收费基于两个成本组成部分：存储和使用(I/O)。
+
您无需为与数据复制(SnapMirror)、备份(SnapVault)或NDMP相关的I/O付费。



ifdef::azure[]

* 在Azure Marketplace中以按需购买或按年订约的形式提供


endif::azure[]

ifdef::gcp[]

* 在Google Cloud Marketplace中以按需购买或按年订约的形式提供


endif::gcp[]

* 增加 NetApp 的任何云数据服务，但需额外付费




==== 专业人员

按容量为任意类型的Cloud Volumes ONTAP 配置付费、备份不受限制。

* 为任何 Cloud Volumes ONTAP 配置提供许可
+
主卷和二级卷的容量充电速度相同的单节点或HA

* 包括使用BlueXP备份和恢复的无限卷备份、但仅适用于使用专业版软件包的Cloud Volumes ONTAP系统。
+

NOTE: 要进行BlueXP  备份和恢复、需要订阅按需购买(PAYGO)、但使用此服务不会产生任何费用。有关为BlueXP  备份和恢复设置许可的详细信息，请参阅 https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html["为BlueXP备份和恢复设置许可"^]。

* 增加 NetApp 的任何云数据服务，但需额外付费




=== 提供基于容量的许可证

要为Cloud Volumes ONTAP系统提供PAYGO和BYOL许可证、需要启动并运行BlueXP  连接器。有关详细信息，请参阅 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#impact-on-cloud-volumes-ontap["了解连接器"^]。



=== 如何开始使用

了解如何开始使用基于容量的许可：

ifdef::aws[]

* link:task-set-up-licensing-aws.html["在AWS中为Cloud Volumes ONTAP 设置许可"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["在Azure中为Cloud Volumes ONTAP 设置许可"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["在Google Cloud中为Cloud Volumes ONTAP 设置许可"]


endif::gcp[]



== Keystone订阅

一种按需购买，基于订阅的服务，可为那些倾向于采用运营支出消费模式而不是前期资本支出或租赁模式的客户提供无缝的混合云体验。

收费基于Keystone订阅中一个或多个Cloud Volumes ONTAP HA对的已提交容量大小。

系统会定期汇总每个卷的已配置容量并将其与Keystone订阅上的已提交容量进行比较、任何超时容量都会在Keystone订阅上按突发容量收费。

link:https://docs.netapp.com/us-en/keystone-staas/index.html["详细了解NetApp Keystone"^]。



=== 支持的配置

HA对支持Keystone订阅。目前，单节点系统不支持此许可选项。



=== Capacity limit

每个单独的 Cloud Volumes ONTAP 系统通过磁盘和对象存储分层支持高达 2 PiB 的容量。



=== 如何开始使用

了解如何开始使用Keystone订阅：

ifdef::aws[]

* link:task-set-up-licensing-aws.html["在AWS中为Cloud Volumes ONTAP 设置许可"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["在Azure中为Cloud Volumes ONTAP 设置许可"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["在Google Cloud中为Cloud Volumes ONTAP 设置许可"]


endif::gcp[]



== 基于节点的许可

基于节点的许可是上一代许可模式，可用于按节点许可 Cloud Volumes ONTAP 。此许可模式不适用于新客户。按节点充电已被上述按容量充电方法所取代。

NetApp已计划终止提供(EOA)并支持(EOS)基于节点的许可。在EOA和EOS之后、需要将基于节点的许可证转换为基于容量的许可证。

有关信息，请参见 https://mysupport.netapp.com/info/communications/CPC-00589.html["中国共产党中央政治局常委、国务院"^]。



=== 基于节点的许可证终止提供

从2024年11月11日开始、基于节点的许可证的有限可用性已终止。基于节点的许可支持将于2024年12月31日结束。

如果您拥有一个有效的基于节点的合同、并且该合同已延长到EOA日期之后、您可以继续使用该许可证、直到该合同到期为止。合同到期后、必须过渡到基于容量的许可模式。如果您没有Cloud Volumes ONTAP节点的长期合同、请务必在EOS日期之前规划您的转换。

从下表中详细了解每种许可证类型以及EOA对其的影响：

[cols="2*"]
|===
| 许可证类型 | EOA之后的影响 


 a| 
通过自带许可证(BYOL)购买的基于节点的有效许可证
 a| 
许可证有效期至到期。现有未使用的基于节点的许可证可用于部署新的Cloud Volumes ONTAP系统。



 a| 
通过BYOL购买的基于节点的许可证已过期
 a| 
您无权使用此许可证部署新的Cloud Volumes ONTAP系统。现有系统可能会继续工作、但在EOS日期之后、您将不会收到任何系统支持或更新。



 a| 
基于节点的有效许可证、含PAYGO订阅
 a| 
将在EOS日期后停止接收NetApp支持、直到您过渡到基于容量的许可证为止。

|===
.除外事项
NetApp认识到某些情况需要特别注意、基于节点的许可的EOA和EOS不适用于以下情况：

* 美国公共部门客户
* 在私有模式下部署
* 在AWS中部署Cloud Volumes ONTAP的中国地区


对于这些特定情形、NetApp将提供支持、以满足符合合同义务和运营需求的独特许可要求。


NOTE: 即使在这些情况下、基于节点的新许可证和许可证续订的有效期也最长为自批准之日起一年。



== 许可证转换

通过BlueXP 、可以通过许可证转换工具将基于节点的许可证无缝转换为基于容量的许可证。有关基于节点的许可的EOA的信息，请参见link:concept-licensing.html#end-of-availability-of-node-based-licenses["基于节点的许可证终止提供"]。

在过渡之前、最好先熟悉这两种许可模式之间的差异。基于节点的许可包括每个ONTAP实例的固定容量、这可能会限制灵活性。另一方面、基于容量的许可允许在多个实例之间共享存储池、从而提高灵活性、优化资源利用率、并降低重新分配工作负载时可能面临的经济处罚。基于容量的充电可根据不断变化的存储需求进行无缝调整。

要了解如何执行此转换，请参见link:task-convert-node-capacity.html["将基于Cloud Volumes ONTAP节点的许可证转换为基于容量的许可证"]。


NOTE: 不支持将系统从基于容量的许可转换为基于节点的许可。
