---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage, tiering 
summary: 您可以在 Cloud Volumes ONTAP 系统上激活一次写入、多次读取（ WORM ）存储、以在指定的保留期内以未经修改的形式保留文件。云 WORM 存储由 SnapLock 技术提供支持，这意味着 WORM 文件在文件级别受到保护。 
---
= 了解Cloud Volumes ONTAP上的WORM存储
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在 Cloud Volumes ONTAP 系统上激活一次写入、多次读取（ WORM ）存储、以在指定的保留期内以未经修改的形式保留文件。云 WORM 存储由 SnapLock 技术提供支持，这意味着 WORM 文件在文件级别受到保护。

WORM功能可与自带许可证(Bring Your O自己 的许可证、BYOL)和适用于您的许可证的市场订阅一起使用、无需额外付费。请联系您的NetApp销售代表、将WORM添加到您的当前许可证中。



== WORM 存储的工作原理

将文件提交到 WORM 存储后，即使在保留期限到期后，也无法对其进行修改。防篡改时钟将确定 WORM 文件的保留期已过。

保留期结束后、您将负责删除不再需要的任何文件。



== 激活 WORM 存储

激活WORM存储的方式取决于所使用的Cloud Volumes ONTAP 版本。



=== 9.10.1及更高版本

从Cloud Volumes ONTAP 9.10.1开始、您可以选择在卷级别启用或禁用WORM。

创建新的Cloud Volumes ONTAP 工作环境时、系统会提示您启用或禁用WORM存储：

* 如果在创建工作环境时启用了WORM存储、则从BlueXP创建的每个卷都会启用WORM。但是、您可以使用ONTAP系统管理器或ONTAP命令行界面创建已禁用WORM的卷。
* 如果在创建工作环境时禁用WORM存储、则通过BlueXP 、ONTAP系统管理器或ONTAP命令行界面创建的每个卷都会禁用WORM。




=== 9.10.0及更早版本

您可以在创建新的工作环境时在 Cloud Volumes ONTAP 系统上激活 WORM 存储。从BlueXP创建的每个卷都已启用WORM。您不能在单个卷上禁用WORM存储。



== 将文件提交到 WORM

您可以使用应用程序通过 NFS 或 CIFS 将文件提交到 WORM ，或者使用 ONTAP CLI 自动将文件提交到 WORM 。您还可以使用 WORM 附加文件来保留增量写入的数据，例如日志信息。

在 Cloud Volumes ONTAP 系统上激活 WORM 存储后，必须使用 ONTAP CLI 对 WORM 存储进行所有管理。有关说明，请参阅 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["有关SnapLock的ONTAP文档"^]。



== 在Cloud Volumes ONTAP工作环境中启用WORM

在BlueXP  上创建Cloud Volumes ONTAP工作环境时、您可以启用WORM存储。如果在创建工作环境期间未启用WORM、则也可以在该环境上启用WORM。启用WORM后、您将无法禁用它。

.关于此任务
* WORm在ONTAP 9 10.1及更高版本上受支持。
* ONTAP 9 11.1及更高版本支持带有备份的WORm。


.步骤
. 在"画布"页面上、双击要启用WORM的工作环境的名称。
. 在概述选项卡上，单击功能面板，然后单击*WORM*旁边的铅笔图标。
+
如果系统上已启用WORM、则铅笔图标将被禁用。

. 在*WORM*页面上，设置集群Compliance时钟的保留期限。
+
有关详细信息，请参阅 https://docs.netapp.com/us-en/ontap/snaplock/initialize-complianceclock-task.html["ONTAP文档：初始化Compliance时钟"^]。

. 单击*设置*。


.完成后
您可以在功能面板上验证*WORM*的状态。启用WORM后、SnapLock许可证将自动安装在集群上。您可以在ONTAP系统管理器上查看SnapLock许可证。



== 正在删除WORM文件

您可以使用特权删除功能在保留期间删除WORM文件。

有关说明，请参阅 https://docs.netapp.com/us-en/ontap/snaplock/delete-worm-files-concept.html["ONTAP 文档"^]。



== WORM和数据分层

创建新的Cloud Volumes ONTAP 9.8或更高版本系统时、您可以同时启用数据分层和WORM存储。通过使用WORM存储启用数据分层、您可以将数据分层到云中的对象存储。

您应了解以下有关启用数据分层和WORM存储的信息：

* 分层到对象存储的数据不包括ONTAP WORM功能。要确保端到端WORM功能、您需要正确设置存储分段权限。
* 分层到对象存储的数据不具有WORM功能、这意味着从技术上讲、对存储分段和容器具有完全访问权限的任何人都可以转到并删除ONTAP 分层的对象。
* 启用WORM和分层后、将阻止还原或降级到Cloud Volumes ONTAP 9.8。




== 限制

* Cloud Volumes ONTAP 中的 WORM 存储在 " 可信存储管理员 " 模式下运行。虽然 WORM 文件不受更改或修改的影响，但集群管理员可以删除卷，即使这些卷包含未过期的 WORM 数据也是如此。
* 除了可信存储管理员模式之外， Cloud Volumes ONTAP 中的 WORM 存储还隐式地在 " 可信云管理员 " 模式下运行。云管理员可以直接从云提供商中删除或编辑云存储、从而在WORM数据到期之前将其删除。


.相关链接
* link:reference-worm-snaplock.html["为WORM存储创建防篡改Snapshot副本"]

