---
sidebar: sidebar 
permalink: task-convert-node-capacity.html 
keywords: license conversion, convert node-based to capacity based, by-node to by-capacity, bluexp license conversion for node based 
summary: '基于节点的许可证终止提供(EOA)后、您应使用BlueXP  许可证转换工具过渡到基于容量的许可模式。' 
---
= 将基于节点的许可证转换为基于容量的许可证
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
基于节点的许可证终止提供(EOA)后、您应使用BlueXP  许可证转换工具过渡到基于容量的许可模式。

对于年度或长期承诺、NetApp建议您在EOA日期(2024年11月11日)或许可证到期日期之前联系NetApp代表、以确保满足过渡的前提条件。如果您没有Cloud Volumes ONTAP节点的长期合同、并根据按需按需按需购买(PAYGO)订阅运行系统、请务必在2024年12月31日支持结束(EOS)之前规划您的转换。在这两种情况下、在使用BlueXP  许可证转换工具进行无缝过渡之前、您都应确保系统满足要求。

有关EOA和EOS的信息，请参阅link:concept-licensing.html#end-of-availability-of-node-based-licenses["基于节点的许可证终止提供"]。

.关于此任务
* 使用许可证转换工具时、可以从基于节点的许可模式原位联机过渡到基于容量的许可模式、从而无需进行任何数据迁移或配置额外的云资源。
* 这是一种无中断运行、不会发生服务中断或应用程序停机。
* Cloud Volumes ONTAP系统中的帐户和应用程序数据保持不变。
* 底层云资源在转换后不受影响。
* 许可证转换工具支持所有部署类型、例如单节点、单可用性区域(AZ)中的高可用性(HA)、多可用性区域(AZ)中的高可用性(HA)、自带许可证(BYOL)和PAYGO)。
* 该工具支持所有基于节点的许可证作为源、支持所有基于容量的许可证作为目标。例如、如果您拥有基于PAYGO标准节点的许可证、则可以将其转换为基于BYOL容量的许可证。
* 所有云提供商、AWS、Azure和Google Cloud均支持此转换。
* 转换后、基于节点的许可证的序列号将替换为基于容量的格式。此操作会在转换过程中完成、并反映在您的NetApp支持站点(NSS)帐户中。
* 过渡到基于容量的模式后、数据将继续保留在与基于节点的许可相同的位置。这种方法可确保数据放置不会中断、并在整个过渡期间遵循数据主权原则。


.开始之前
* 您应具有具有客户访问权限或管理员访问权限的NSS帐户。
* 您的NSS帐户应使用BlueXP  用户凭据进行注册。
* 工作环境应链接到具有客户访问权限或管理员访问权限的NSS帐户。
* 您应拥有有效的基于容量的许可证、可以是BYOL许可证、也可以是Marketplace订阅。
* BlueXP  帐户中应提供基于容量的许可证。此许可证可以是市场订阅或BlueXP  数字钱包中的BYOL/私人优惠包。
* 在选择目标软件包之前、请了解以下标准：
+
** 如果帐户具有基于容量的BYOL许可证、则选定的目标软件包应与帐户的基于容量的BYOL许可证一致：
+
***  `Professional`如果选择作为目标软件包、则帐户应具有具有专业版软件包的BYOL许可证：
***  `Essentials`如果选择作为目标软件包、则帐户应具有包含Essentials软件包的BYOL许可证。
***  `Optimized`如果选择作为目标软件包、则帐户应具有包含优化软件包的BYOL许可证。


** 如果目标许可证包与帐户的BYOL许可证可用性不一致、则表示基于容量的许可证可能不包括选定的许可证包。在这种情况下、我们将通过您的商城订阅向您收费。
** 如果没有基于容量的BYOL许可证、而只有一个Marketplace订阅、则您应确保所选软件包包含在基于容量的Marketplace订阅中。
** 如果您现有的基于容量的许可证没有足够的容量、并且您有一个商城订阅可按额外容量使用量收费、则您将通过商城订阅按额外容量收费。
** 如果现有基于容量的许可证容量不足、并且您没有市场订阅来为额外的容量使用量收费、则无法进行转换。您应添加商城订阅以收取额外容量费用或将可用容量扩展到当前许可证。
** 如果目标许可证包与帐户的BYOL许可证可用性不一致、并且现有基于容量的许可证容量不足、则您将通过商城订阅付费。





NOTE: 如果未满足上述任何要求、则不会进行许可证转换。在特定情况下、许可证可以转换、但不能使用。单击信息图标以确定问题并采取更正操作。

.步骤
. 在"画布"页面上、双击要修改许可证类型的工作环境的名称。
. 在概述选项卡上、单击功能面板。
. 检查*充电方法*旁边的铅笔图标。如果系统的充电方式是 `Node Based`，则可以将其转换为按容量充电。
+

TIP: 如果Cloud Volumes ONTAP系统已按容量付费、或者未满足任何要求、则此图标将被禁用。

. 在*将基于节点的许可证转换为基于容量的许可证*屏幕上，验证工作环境名称和源许可证详细信息。
. 选择用于转换现有许可证的目标软件包：
+
** 要点。默认值为 `Essentials`。
** 专业人员




ifdef::azure[]

* 优化(适用于Azure)


endif::azure[]

ifdef::gcp[]

* 优化(适用于Google Cloud)


endif::gcp[]

. 如果您拥有BYOL许可证、则可以选中此复选框、以便在转换后从BlueXP  数字钱包中删除基于节点的许可证。如果转换未完成、则即使选中此复选框、许可证也不会从数字钱包中删除。如果您有商城订阅、则此选项不可用。
. 选中此复选框以确认您了解更改的含义，然后单击*Proce*。


.完成后
查看新许可证序列号并验证BlueXP  数字钱包中的更改。
