---
sidebar: sidebar 
permalink: task-accelerate-data-access.html 
keywords: flexcache, flexcache volumes, create a flexcache volume, provision flexcache, create flexcache volume 
summary: FlexCache 卷是一种存储卷，用于缓存原始卷或源卷中的 NFS 读取数据。后续读取缓存的数据会加快对该数据的访问速度。 
---
= 利用 FlexCache 卷加快数据访问速度
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FlexCache卷是一种存储卷、用于缓存来自初始(或源)卷的SMB和NFS读取数据。后续读取缓存的数据会加快对该数据的访问速度。

您可以使用 FlexCache 卷加快数据访问速度，或者从访问量较多的卷卸载流量。FlexCache 卷有助于提高性能，尤其是在客户端需要重复访问相同数据时，因为可以直接提供数据，而无需访问原始卷。FlexCache 卷非常适合读取密集型系统工作负载。

BlueXP可通过管理FlexCache卷 link:https://docs.netapp.com/us-en/bluexp-volume-caching/index.html["BlueXP卷缓存"^] 服务

您还可以使用ONTAP命令行界面或ONTAP系统管理器创建和管理FlexCache卷：

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["《 FlexCache 卷加快数据访问高级指南》"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["在 System Manager 中创建 FlexCache 卷"^]


video::PBNPVRUeT1o[youtube,width=848,height=480]


== 在源站加密后使用FlexCache

在初始卷已加密的Cloud Volumes ONTAP系统上配置FlexCache时、需要执行其他步骤、以确保FlexCache卷可以正确访问和缓存加密数据。

.开始之前
. *加密设置*：确保源卷已完全加密且正常运行。对于Cloud Volumes ONTAP系统、这涉及到与云专用密钥管理服务集成。


ifdef::aws[]

对于AWS、这通常意味着使用AWS密钥管理服务(Key Management Service、KMS)。有关信息，请参见 link:task-aws-key-management.html["使用AWS密钥管理服务管理密钥"]。

endif::aws[]

ifdef::azure[]

对于Azure、您需要为NetApp卷加密(NVE)设置Azure密钥存储。有关信息，请参见 link:task-azure-key-vault.html["使用Azure密钥存储管理密钥"]。

endif::azure[]

ifdef::gcp[]

对于Google Cloud、它是Google Cloud密钥管理服务。有关信息，请参见 link:task-google-key-manager.html["使用Google的云密钥管理服务管理密钥"]。

endif::gcp[]

. *密钥管理服务*：创建FlexCache卷之前，请验证是否已在Cloud Volumes ONTAP系统上正确配置密钥管理服务。此配置对于FlexCache卷对初始卷中的数据进行解密至关重要。
. *许可*：确认Cloud Volumes ONTAP系统上有有效的FlexCache许可证并已激活。
. * ONTAP版本*：确保Cloud Volumes ONTAP系统的ONTAP版本支持带有加密卷的FlexCache。有关详细信息、请参见最新 https://docs.netapp.com/us-en/ontap/release-notes/index.html["《 ONTAP 发行说明》"^] 或兼容性列表。
. *网络配置*：确保网络配置允许初始卷和FlexCache卷之间无缝通信。这包括在云环境中正确路由和DNS解析。


.步骤
在Cloud Volumes ONTAP系统上使用加密的源卷创建FlexCache卷。有关详细步骤和其他注意事项、请参阅以下各节：

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["《 FlexCache 卷加快数据访问高级指南》"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["在 System Manager 中创建 FlexCache 卷"^]

