---
sidebar: sidebar 
permalink: task-managing-svms-azure.html 
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported 
summary: Storage VM 是在 ONTAP 中运行的虚拟机，可为客户端提供存储和数据服务。您可能会将其视为 SVM 或 SVM 。默认情况下， Cloud Volumes ONTAP 配置有一个 Storage VM ，但某些配置支持额外的 Storage VM 。 
---
= 在Azure中管理为Cloud Volumes ONTAP提供数据的Storage VM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Storage VM 是在 ONTAP 中运行的虚拟机，可为客户端提供存储和数据服务。您可能会将其识别为 _svm_ 或 _vserver_ 。默认情况下、Cloud Volumes ONTAP配置有一个Storage VM、但在Azure中运行Cloud Volumes ONTAP时、您可以创建其他Storage VM。

要在Azure中创建和管理其他提供数据的Storage VM、应使用BlueXP  API。这是因为API可自动执行创建Storage VM和配置所需网络接口的过程。创建Storage VM时、BlueXP  会配置所需的LIF服务以及从Storage VM进行出站SMB/Cifs通信所需的iSCSI LIF。

有关运行Cloud Volumes ONTAP API调用的信息，请参见 https://docs.netapp.com/us-en/bluexp-automation/cm/your_api_call.html#step-1-select-the-identifie["您的第一次API调用"^]。



== 支持的 Storage VM 数量

从Cloud Volumes ONTAP 9.0.0开始、根据您的许可证、特定配置支持多个Storage VM。请参见 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-azure.html["《 Cloud Volumes ONTAP 发行说明》"^]以验证您的Cloud Volumes ONTAP版本支持的Storage VM数量。

所有Cloud Volumes ONTAP先前版本的9.9.0均支持一个提供数据的Storage VM和一个用于灾难恢复的目标Storage VM。如果源 Storage VM 发生中断，您可以激活目标 Storage VM 以进行数据访问。



== 创建Storage VM

根据您的配置和许可证类型、您可以使用BlueXP  API在单节点系统上或高可用性(HA)配置中创建多个Storage VM。

.关于此任务
在使用API创建Storage VM并配置所需的网络接口时、BlueXP  还会修改 `default-data-files`数据Storage VM上的策略、方法是从NAS数据LIF中删除以下服务、然后将其添加到用于出站管理连接的iSCSI数据LIF中：

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`


.开始之前
要为Cloud Volumes ONTAP创建Storage VM、此连接器需要特定权限。所需的权限包括在中 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html["NetApp 提供的策略"^]。



=== 单节点系统

使用以下API调用在单节点系统上创建Storage VM。

`POST /azure/vsa/working-environments/{workingEnvironmentId}/svm`

在请求正文中包括以下参数：

[source, json]
----
{ "svmName": "myNewSvm1"
   "svmPassword": "optional, the API takes the cluster password if not provided"
   "mgmtLif": "optional, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


=== HA 对

使用以下API调用在HA对上创建Storage VM：

`POST /azure/ha/working-environments/{workingEnvironmentId}/svm`

在请求正文中包括以下参数：

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
   "mgmtLif": "optional value, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


== 管理单节点系统和HA对上的Storage VM

通过使用BlueXP  API、您可以在单节点和HA配置中重命名和删除Storage VM。

.开始之前
连接器需要特定权限才能管理Cloud Volumes ONTAP的Storage VM。所需的权限包括在中 https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html["NetApp 提供的策略"^]。



=== 重命名Storage VM

要重命名Storage VM、应提供现有Storage VM和新Storage VM的名称作为参数。

.步骤
* 使用以下API调用重命名单节点系统上的Storage VM：
+
`PUT /azure/vsa/working-environments/{workingEnvironmentId}/svm`

+
在请求正文中包括以下参数：

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----
* 使用以下API调用重命名HA对上的Storage VM：
+
`PUT /azure/ha/working-environments/{workingEnvironmentId}/svm`

+
在请求正文中包括以下参数：

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----




=== 删除Storage VM

在单节点或HA配置中、如果Storage VM不具有任何活动卷、则可以将其删除。

.步骤
* 使用以下API调用删除单节点系统上的Storage VM：
+
`DELETE /azure/vsa/working-environments/{workingEnvironmentId}/svm/{svmName}`

* 使用以下API调用删除HA对上的Storage VM：
+
`DELETE /azure/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`



.相关信息
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html["准备使用 API"^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows["Cloud Volumes ONTAP工作流"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/get_identifiers.html#get-the-connector-identifier["获取所需的标识符"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/use_rest_apis.html["使用BlueXP REST API"^]

